CREATE TABLE `vehicle` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `status` int NOT NULL,
  `vehicle_make_id` bigint NOT NULL,
  `vehicle_model_id` bigint NOT NULL,
  `vehicle_type_id` bigint NOT NULL,
  `fuel_type_id` bigint NOT NULL,
  `vehicle_color_id` bigint NOT NULL,
  `description` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `plate_number` varchar(100) DEFAULT NULL,
  `iu_number` varchar(100) DEFAULT NULL,
  `chassis_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `engine_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `num_seats` int NOT NULL,
  `boot_space` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `car_park_id` bigint NOT NULL,
  `asset_owner_id` bigint NOT NULL,
  `price_group_id` bigint NOT NULL,
  `last_service_date` datetime(3) DEFAULT NULL,
  `last_cleaned_date` datetime(3) DEFAULT NULL,
  `telemetry_provider` int NOT NULL,
  `last_service_mileage` int DEFAULT NULL,
  `current_mileage` int DEFAULT NULL,
  `current_fuel_level` int DEFAULT NULL,
  `active_from` datetime(3) DEFAULT NULL,
  `active_to` datetime(3) DEFAULT NULL,
  `created_by` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_by` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `fivetran_deleted` tinyint(1) DEFAULT NULL,
  `old_id` varchar(36) DEFAULT NULL,
  `vehicle_status_id` bigint NOT NULL DEFAULT '1',
  `platform` smallint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `plate_number_UNIQUE` (`plate_number`),
  KEY `IX_vehicle_vehicle_type_id` (`vehicle_type_id`),
  KEY `IX_vehicle_vehicle_make_id` (`vehicle_make_id`),
  KEY `IX_vehicle_vehicle_model_id` (`vehicle_model_id`),
  KEY `IX_vehicle_fuel_type_id` (`fuel_type_id`),
  KEY `IX_vehicle_asset_owner_id` (`asset_owner_id`),
  KEY `IX_vehicle_car_park_id` (`car_park_id`),
  KEY `IX_vehicle_vehicle_color_id` (`vehicle_color_id`),
  KEY `IX_vehicle_price_group_id` (`price_group_id`),
  CONSTRAINT `FK_vehicle_car_asset_owner_asset_owner_id` FOREIGN KEY (`asset_owner_id`) REFERENCES `car_asset_owner` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_vehicle_car_park_car_park_id` FOREIGN KEY (`car_park_id`) REFERENCES `car_park` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_vehicle_fuel_type_fuel_type_id` FOREIGN KEY (`fuel_type_id`) REFERENCES `fuel_type` (`id`),
  CONSTRAINT `FK_vehicle_vehicle_color_vehicle_color_id` FOREIGN KEY (`vehicle_color_id`) REFERENCES `vehicle_color` (`id`),
  CONSTRAINT `FK_vehicle_vehicle_make_vehicle_make_id` FOREIGN KEY (`vehicle_make_id`) REFERENCES `vehicle_make` (`id`),
  CONSTRAINT `FK_vehicle_vehicle_model_vehicle_model_id` FOREIGN KEY (`vehicle_model_id`) REFERENCES `vehicle_model` (`id`),
  CONSTRAINT `FK_vehicle_vehicle_type_vehicle_type_id` FOREIGN KEY (`vehicle_type_id`) REFERENCES `vehicle_type` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
